import 'package:dvir/features/Community/domain/types/community_type.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'community.freezed.dart';
part 'community.g.dart';

/// A community (OSBB, cooperative, residential complex …).
///
/// [inviteCode] is generated by the `create_community` RPC, never by the app —
/// it must stay unique across all communities.
@freezed
abstract class Community with _$Community {
  const factory Community({
    required String id,
    required String name,
    required CommunityType type,
    @JsonKey(name: 'invite_code') required String inviteCode,
    String? address,
    String? city,
  }) = _Community;

  factory Community.fromJson(Map<String, dynamic> json) =>
      _$CommunityFromJson(json);
}
