import 'package:dvir/features/Community/domain/models/community.dart';
import 'package:dvir/features/Community/domain/types/community_type.dart';
import 'package:dvir/features/Onboarding/domain/models/scope_membership.dart';
import 'package:dvir/features/Units/domain/models/unit.dart';
import 'package:dvir/features/Units/domain/types/unit_type.dart';

/// Contract for getting a new user somewhere (Base): creating a scope, or
/// entering an existing one with a code.
abstract interface class OnboardingRepository {
  /// Where the signed-in user belongs, or null while they belong nowhere.
  ///
  /// A stream rather than a future because the waiting screen should one day
  /// advance by itself the moment an admin approves the request. Today it
  /// emits once; swapping in a realtime subscription changes only the
  /// implementation.
  Stream<ScopeMembership?> watchMyMembership();

  /// Creates a community with the caller as its first admin. The invite code is
  /// generated by the backend.
  Future<Community> createCommunity({
    required String name,
    required CommunityType type,
    String? address,
    String? city,
  });

  /// Creates an object with the caller as its owner.
  ///
  /// Three shapes, decided by what is passed: inside [parentId] (inherits that
  /// object's community), inside [communityId] (admins only), or neither — a
  /// standalone object belonging to no community at all.
  Future<Unit> createUnit({
    required String label,
    required UnitType type,
    String? parentId,
    String? communityId,
    String? address,
    String? city,
    double? areaM2,
  });

  /// Sends a join request for whatever the code opens — a community or an
  /// object. The backend decides which; the caller finds out from the result.
  Future<ScopeMembership> joinByInvite(String inviteCode);
}
